---
title: "Data import"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import a dataset.

```{r}
litters_df =
  read_csv("data_import_examples/FAS_litters.csv")
```

Look at your data!

```{r}
names(litters_df)
```

Update the names in `litters_df`

```{r}
litters_df =
   janitor::clean_names(litters_df)
```

Sometimes skimming data is neat?
```{r}
skimr::skim(litters_df)
```

##Fix the missingness

```{r}
litters_df = 
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA",".",""))
```

##Trying this by myself

```{r}
pups_df = 
  read_csv(
      "data_import_examples/FAS_pups.csv", 
      na = c("NA",".",""), 
      skip = 3
      )

pups_df =
  janitor::clean_names(pups_df)
```

## okay what about excel

CSVs are really great but sometimes you get an excel file.
(which sucks)

```{r}
mlb_df = 
  read_excel("data_import_examples/mlb11.xlsx")
```

import LOTR

```{r}
lotr_df = 
  read_excel("data_import_examples/LotR_Words.xlsx", range = "B3:D6")
```

##SAS???


Import the PULSE data

```{r}
pulse_df = 
  read_sas("data_import_examples/public_pulse_data.sas7bdat")

pulse_df = 
  janitor::clean_names(pulse_df)
```

##Why do I hate read.csv (btw i used this for 5 years)



